name: CMakeRPi

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: pguyot/arm-runner-action@v2
      id: build
      with:
        base_image: raspbian_lite:latest
        image_additional_mb: 1024
        commands: |
          sudo apt-get update
          sudo apt-get install cmake mesa-common-dev libxxf86vm-dev freeglut3-dev libxext-dev libxcursor-dev portaudio19-dev libsndfile1-dev
          cd src
          sed -i 's/#add_definitions(-DFOR_DEB)/add_definitions(-DFOR_DEB)/g' CMakeLists.txt
          cat CMakeLists.txt
          cd ../bin
          cmake ../src
          make
          ./bridgecommand --version
          cd createDeb
          ./buildDeb
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux-arm
        path: bin/createDeb/bridgecommand.deb
